Add integration testing w/external NextJS app (Edge runtime) (#304)
## Problem

We do not currently have a good way to test how our client behaves end
to end in different environments. One of the chief problems our users
have brought to our attention in the past is that some functionalities
do not work in certain runtimes, e.g. Edge or Bun, and/or with certain
frameworks, e.g. [NextJS](https://nextjs.org/docs).

## Solution

Build an external application in a runtime and framework known to have
caused problems in the past and test our client from the end-user's
perspective.

This PR introduces and end-to-end test suite that interacts with an
external application written using the NextJS framework and the
[Edge](https://vercel.com/docs/functions/edge-middleware/edge-runtime#edge-runtime)
runtime.

Note: the app is automagically run in `Edge` by way of it using
[middleware](https://nextjs.org/docs/app/building-your-application/routing/middleware)
(`middleware.ts`), and the [`Headers()`
API](https://developer.mozilla.org/en-US/docs/Web/API/Headers).

## Overview of changes
- We now have [a public
repo](https://github.com/pinecone-io/ts-client-e2e-tests) that contains
a super simple application that builds a Pinecone serverless index,
seeds it with data, and queries that data. We plan to add more
operations in the near future; this is just a start.
- This sample application creates an API endpoint that our client repo
can send a POST request to and assert on the response. If the endpoint
fails to deliver the expected response, we know that something is wrong
with the most recent changes we are proposing to introduce in the
client.
- This PR enables 2 types of interaction with the sample application:
- Local end-to-end tests: for local runs, there is a new bash script
that devs can execute. This will spin up the application on their
`localhost:3000`.
- CI end-to-end tests: for CI runs, we will now run this test
automatically by way of adding it the `testing.yml` file that is run for
each push to an open PR. In CI, the Github workflow and action hit the
application's Vercel endpoint and assert on its response.
- There is a new CONTRIBUTING.md file with some info on this new test
suite + the other existing ones, as well as a new README in the
`external-app` dir itself with more in depth information.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Infrastructure change (CI configs, etc)
- [x] Non-code change (docs, etc)
- [ ] None of the above: (explain here)

## Test Plan

If reviewers can pull down the code in this branch and try to run the
tests locally, that'd be great.

## To Dos
I'll add a README and a CONTRIBUTING file to [the external
app](https://github.com/pinecone-io/ts-client-e2e-tests)

---
- To see the specific tasks where the Asana app for GitHub is being
used, see below:
  - https://app.asana.com/0/0/1208129226784956

diff --git a/.github/actions/e2e-testing/edge/action.yml b/.github/actions/e2e-testing/edge/action.yml
--- a/.github/actions/e2e-testing/edge/action.yml
+++ b/.github/actions/e2e-testing/edge/action.yml
@@ -3,6 +3,10 @@ name: Spin up Vercel App
 inputs:
   vercel-token:
     required: true
+    description: 'Vercel token to deploy the app'
+  PINECONE_API_KEY:
+    required: true
+    description: 'Pinecone API key to send requests to the Vercel app'
 
 runs:
   using: 'composite'
@@ -27,27 +31,55 @@ runs:
       uses: GuillaumeFalourd/clone-github-repo-action@main
       with:
         owner: 'pinecone-io'
-        repository: 'pinecone-rag-demo'
+        repository: 'ts-client-test-external-app'
         branch: 'main'
 
-    - name: Move package to pinecone-rag-demo
-      run: cd pinecone-rag-demo && mv ../pinecone-database-pinecone-*.tgz .
+    - name: Install Vercel app dependencies
+      run: cd ts-client-test-external-app && npm install
       shell: bash
 
-    - name: Install rag-demo deps
-      run: cd pinecone-rag-demo && npm install
+    - name: Move packed ts-client code into the Vercel app dir
+      run: cd ts-client-test-external-app && mv ../pinecone-database-pinecone-*.tgz .
       shell: bash
 
-    - name: Install pinecone-ts-client "main" branch code into the Vercel app
-      run: cd pinecone-rag-demo && npm install pinecone-database-pinecone-*.tgz
-      shell: bash
-
-    - name: Install Vercel CLI
-      run: cd pinecone-rag-demo && npm install vercel
-      shell: bash
-
-    - name: Deploy Project Artifacts to Vercel
+    - name: Install ts-client code into the Vercel app's package.json file
       run: |
-        cd pinecone-rag-demo
-        vercel --scope=pinecone-io --token=${{ inputs.vercel-token }} --yes
+        cd ts-client-test-external-app
+        npm install pinecone-database-pinecone-*.tgz
+      shell: bash
+
+    - name: Install Vercel CLI and (re)deploy the app
+      run: |
+        cd ts-client-test-external-app
+        npm install vercel
+        vercel --token ${{ inputs.vercel-token }}
+        vercel pull --yes --token ${{ inputs.vercel-token }}
+        vercel build --token ${{ inputs.vercel-token }}
+        vercel --token ${{ inputs.vercel-token }} --prod
+      shell: bash
+
+    - name: Hit Vercel app endpoint(s) via assertResponse.ts file
+      run: |
+        npm install -g typescript
+        npm install -g ts-node
+        export PINECONE_API_KEY="${{ inputs.PINECONE_API_KEY }}"
+        ciUrl='http://ts-client-test-external-app.vercel.app/api/createSeedQuery'
+        indexName=$(ts-node src/external-app/assertResponse.ts "$ciUrl"| grep -v "Test passed!")
+        echo "indexName=$indexName" >> $GITHUB_ENV
+      shell: bash
+
+    - name: Clean up test index(es)
+      run: |
+        PINECONE_API_KEY="${{ inputs.PINECONE_API_KEY }}"
+        matching_index="${{ env.indexName }}"
+
+        delete_response=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE "https://api.pinecone.io/indexes/$matching_index" \
+        -H "Api-Key: $PINECONE_API_KEY")
+
+        if [ "$delete_response" -eq 202 ]; then
+          echo "Successfully deleted index: $matching_index"
+        else
+          echo "Failed to delete index: $matching_index. HTTP status code: $delete_response"
+          exit 1
+        fi
       shell: bash
